platform:
  BTC:
    blockExplorerAddrUrl: https://live.blockcypher.com/btc/address/
    blockExplorerTxUrl: https://live.blockcypher.com/btc/tx/
    blockExplorerUrl: https://live.blockcypher.com/btc/
    bytes: 226
    chain: BTC
    chainId: ''
    coinId: 0
    decimal: 8
    fullName: Bitcoin
    getPriceKey: bitcoin
    handler: bitcoin
    icon: https://obstatic.243096.com/mili/images/currency/chain/Bitcoin.png
    nativeCurrency: BTC
    netType: main
    proxyCacheTime: 60
    proxyKey: feeOracleBTC
    rpcURL:
      - https://api.blockcypher.com/v1/btc/main
      - https://Bearer:9VpB0M4Al-RNmiOvFHwOMvNNetBfZY2mDepbbXT2ygBJ2-AG@svc.blockdaemon.com/universal/v1/bitcoin/mainnet/
    standbyRPCURL:
      - https://chain.so/
    symbol: BTC
    type: BTC
    safelyConcurrentBlockDelta: 6
    maxConcurrency: 5
    monitorHeightAlarmThr: 12
  DOGE:
    blockExplorerAddrUrl: https://dogechain.info/address/
    blockExplorerTxUrl: https://dogechain.info/tx/
    blockExplorerUrl: https://dogechain.info/
    chain: DOGE
    chainId: ''
    coinId: 0
    decimal: 8
    fullName: Dogecoin
    getPriceKey: dogecoin
    handler: dogecoin
    nativeCurrency: DOGE
    netType: main
    proxyCacheTime: 60
    rpcURL:
      - https://zpka_a96686455d374da6a418f65eaca8a0a5_1652e9a7@svc.blockdaemon.com/universal/v1/dogecoin/mainnet/
      - https://zpka_2991d45e50054722ba547e54e739a7e8_41cff525@svc.blockdaemon.com/universal/v1/dogecoin/mainnet/
      - https://zpka_630c27c7492847b18b0b21aa346fc0ab_011359a9@svc.blockdaemon.com/universal/v1/dogecoin/mainnet/
      - https://zpka_8976bc36b6c84ef6b493460b1dc4a8ce_4e56d164@svc.blockdaemon.com/universal/v1/dogecoin/mainnet/
      - https://zpka_ea8d8727c06349e6b93d939d328e0e04_4085b24f@svc.blockdaemon.com/universal/v1/dogecoin/mainnet/
    standbyRPCURL:
      - https://chain.so/
    symbol: DOGE
    type: BTC
    safelyConcurrentBlockDelta: 6
    maxConcurrency: 5
    monitorHeightAlarmThr: 12

  LTC:
    blockExplorerAddrUrl: https://live.blockcypher.com/ltc/address/
    blockExplorerTxUrl: https://live.blockcypher.com/ltc/tx/
    blockExplorerUrl: https://live.blockcypher.com/ltc/
    bytes: 226
    chain: LTC
    chainId: ''
    coinId: 2
    decimal: 8
    fullName: Litecoin
    getPriceKey: litecoin
    handler: litecoin
    icon: https://obstatic.243096.com/mili/images/currency/chain/Bitcoin.png
    nativeCurrency: LTC
    netType: main
    proxyCacheTime: 60
    proxyKey: feeOracleLTC
    rpcURL:
      - https://zpka_a96686455d374da6a418f65eaca8a0a5_1652e9a7@svc.blockdaemon.com/universal/v1/litecoin/mainnet/
      - https://zpka_2991d45e50054722ba547e54e739a7e8_41cff525@svc.blockdaemon.com/universal/v1/litecoin/mainnet/
      - https://zpka_630c27c7492847b18b0b21aa346fc0ab_011359a9@svc.blockdaemon.com/universal/v1/litecoin/mainnet/
      - https://zpka_8976bc36b6c84ef6b493460b1dc4a8ce_4e56d164@svc.blockdaemon.com/universal/v1/litecoin/mainnet/
      - https://zpka_ea8d8727c06349e6b93d939d328e0e04_4085b24f@svc.blockdaemon.com/universal/v1/litecoin/mainnet/
    standbyRPCURL:
      - https://chain.so/
    symbol: LTC
    type: BTC
    safelyConcurrentBlockDelta: 6
    maxConcurrency: 5
    monitorHeightAlarmThr: 12

platformTest:
  ScrollL2TEST:
    blockExplorerAddrUrl: https://l2scan.scroll.io/address
    blockExplorerTxUrl: https://l2scan.scroll.io/tx
    blockExplorerUrl: https://l2scan.scroll.io
    categoryName: EVM
    chain: ScrollL2TEST
    chainId: "534354"
    coinId: 60
    decimal: 18
    customNonce: true
    fullName: Scroll L2 Test Net
    getPriceKey: ethereum
    handler: scroll
    icon: https://obstatic.243096.com/mili/images/currency/chain/Scroll.jpeg
    nativeCurrency: TSETH
    netType: test
    proxyCacheTime: 0
    rpcURL:
      - https://prealpha.scroll.io/l2
    symbol: Scroll L2
    type: EVM
    safelyConcurrentBlockDelta: 20
    maxConcurrency: 1
