// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"block-crawling/internal/biz"
	"block-crawling/internal/conf"
	"block-crawling/internal/data"
	logger "block-crawling/internal/log"
	"block-crawling/internal/platform"
)

// Injectors from wire.go:

// wireApp init kratos application.

func wireApp(confLogger *conf.Logger, confData *conf.Data, confApp *conf.App, confInnerNodeList map[string]*conf.PlatInfo, confInnerPublicNodeList map[string]*conf.PlatInfo, confPlatform map[string]*conf.PlatInfo,
	confPlatformTest map[string]*conf.PlatInfo) (func(), error) {
	logger.NewLogger(confLogger)
	gormDB, cleanup, err := data.NewGormDB(confData)
	if err != nil {
		return nil, err
	}
	data.NewRedisClient(confData)
	biz.NewConfig(confApp)
	platform.NewPlatform(confInnerPublicNodeList, confPlatform, confPlatformTest)
	platform.NewInnerNodeList(confInnerNodeList)
	data.NewBtcTransactionRecordRepo(gormDB)
	data.NewEvmTransactionRecordRepo(gormDB)
	data.NewStcTransactionRecordRepo(gormDB)
	data.NewTrxTransactionRecordRepo(gormDB)
	data.NewDappApproveRecordRepo(gormDB)
	data.NewUtxoUnspentRecordRepo(gormDB)
	data.NewUserAssetRepo(gormDB)
	data.NewNervosCellRecordRepo(gormDB)
	data.NewUserNftAssetRepo(gormDB)
	data.NewNftRecordHistoryRepo(gormDB)
	data.NewCsprTransactionRecordRepo(gormDB)


	return func() {
		cleanup()
	}, nil
}
