// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: bfstation/v1/bfstation.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BFStationClient is the client API for BFStation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BFStationClient interface {
	PageListTxns(ctx context.Context, in *PageListTxnsRequest, opts ...grpc.CallOption) (*PageListTxnsResponse, error)
	CountPoolHolders(ctx context.Context, in *PoolHolderRequest, opts ...grpc.CallOption) (*CountResponse, error)
	CountTokenHolders(ctx context.Context, in *TokenHolderRequest, opts ...grpc.CallOption) (*CountResponse, error)
	PageListCollectFees(ctx context.Context, in *PageListFeesRequest, opts ...grpc.CallOption) (*PageListFeesResponse, error)
}

type bFStationClient struct {
	cc grpc.ClientConnInterface
}

func NewBFStationClient(cc grpc.ClientConnInterface) BFStationClient {
	return &bFStationClient{cc}
}

func (c *bFStationClient) PageListTxns(ctx context.Context, in *PageListTxnsRequest, opts ...grpc.CallOption) (*PageListTxnsResponse, error) {
	out := new(PageListTxnsResponse)
	err := c.cc.Invoke(ctx, "/api.bfstation.v1.BFStation/PageListTxns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFStationClient) CountPoolHolders(ctx context.Context, in *PoolHolderRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, "/api.bfstation.v1.BFStation/CountPoolHolders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFStationClient) CountTokenHolders(ctx context.Context, in *TokenHolderRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, "/api.bfstation.v1.BFStation/CountTokenHolders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFStationClient) PageListCollectFees(ctx context.Context, in *PageListFeesRequest, opts ...grpc.CallOption) (*PageListFeesResponse, error) {
	out := new(PageListFeesResponse)
	err := c.cc.Invoke(ctx, "/api.bfstation.v1.BFStation/PageListCollectFees", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BFStationServer is the server API for BFStation service.
// All implementations must embed UnimplementedBFStationServer
// for forward compatibility
type BFStationServer interface {
	PageListTxns(context.Context, *PageListTxnsRequest) (*PageListTxnsResponse, error)
	CountPoolHolders(context.Context, *PoolHolderRequest) (*CountResponse, error)
	CountTokenHolders(context.Context, *TokenHolderRequest) (*CountResponse, error)
	PageListCollectFees(context.Context, *PageListFeesRequest) (*PageListFeesResponse, error)
	mustEmbedUnimplementedBFStationServer()
}

// UnimplementedBFStationServer must be embedded to have forward compatible implementations.
type UnimplementedBFStationServer struct {
}

func (UnimplementedBFStationServer) PageListTxns(context.Context, *PageListTxnsRequest) (*PageListTxnsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageListTxns not implemented")
}
func (UnimplementedBFStationServer) CountPoolHolders(context.Context, *PoolHolderRequest) (*CountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountPoolHolders not implemented")
}
func (UnimplementedBFStationServer) CountTokenHolders(context.Context, *TokenHolderRequest) (*CountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountTokenHolders not implemented")
}
func (UnimplementedBFStationServer) PageListCollectFees(context.Context, *PageListFeesRequest) (*PageListFeesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageListCollectFees not implemented")
}
func (UnimplementedBFStationServer) mustEmbedUnimplementedBFStationServer() {}

// UnsafeBFStationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BFStationServer will
// result in compilation errors.
type UnsafeBFStationServer interface {
	mustEmbedUnimplementedBFStationServer()
}

func RegisterBFStationServer(s grpc.ServiceRegistrar, srv BFStationServer) {
	s.RegisterService(&BFStation_ServiceDesc, srv)
}

func _BFStation_PageListTxns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageListTxnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFStationServer).PageListTxns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.bfstation.v1.BFStation/PageListTxns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFStationServer).PageListTxns(ctx, req.(*PageListTxnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFStation_CountPoolHolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolHolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFStationServer).CountPoolHolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.bfstation.v1.BFStation/CountPoolHolders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFStationServer).CountPoolHolders(ctx, req.(*PoolHolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFStation_CountTokenHolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenHolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFStationServer).CountTokenHolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.bfstation.v1.BFStation/CountTokenHolders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFStationServer).CountTokenHolders(ctx, req.(*TokenHolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFStation_PageListCollectFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageListFeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFStationServer).PageListCollectFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.bfstation.v1.BFStation/PageListCollectFees",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFStationServer).PageListCollectFees(ctx, req.(*PageListFeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BFStation_ServiceDesc is the grpc.ServiceDesc for BFStation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BFStation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.bfstation.v1.BFStation",
	HandlerType: (*BFStationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PageListTxns",
			Handler:    _BFStation_PageListTxns_Handler,
		},
		{
			MethodName: "CountPoolHolders",
			Handler:    _BFStation_CountPoolHolders_Handler,
		},
		{
			MethodName: "CountTokenHolders",
			Handler:    _BFStation_CountTokenHolders_Handler,
		},
		{
			MethodName: "PageListCollectFees",
			Handler:    _BFStation_PageListCollectFees_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bfstation/v1/bfstation.proto",
}
