platform:
  BSC:
    blockExplorerAddrUrl: https://bscscan.com/address/
    blockExplorerTxUrl: https://bscscan.com/tx/
    blockExplorerUrl: https://bscscan.com/
    chain: BSC
    chainId: "56"
    coinId: 60
    decimal: 18
    fullName: Binance Smart Chain
    getPriceKey: binancecoin
    handler: bsc
    icon: https://obstatic.243096.com/mili/images/currency/chain/BSC.png
    nativeCurrency: BNB
    netType: main
    proxyCacheTime: 15
    proxyKey: gasOracleBsc
    rpcURL:
    - https://rpc.ankr.com/bsc
    - https://bsc.mytokenpocket.vip
    - https://rpc-bsc.bnb48.club
    - https://bscrpc.com
    - https://binance.ankr.com
    - https://bsc-dataseed.defibit.io
    - https://bsc-dataseed1.defibit.io
    - https://bsc-dataseed2.defibit.io
    - https://bsc-dataseed3.defibit.io
    - https://bsc-dataseed4.defibit.io
    - https://bsc-dataseed.binance.org
    - https://bsc-dataseed1.binance.org
    - https://bsc-dataseed2.binance.org
    - https://bsc-dataseed3.binance.org
    - https://bsc-dataseed4.binance.org
    - https://bsc-dataseed.ninicoin.io
    - https://bsc-dataseed1.ninicoin.io
    - https://bsc-dataseed2.ninicoin.io
    - https://bsc-dataseed3.ninicoin.io
    - https://bsc-dataseed4.ninicoin.io
    - https://bsc-dataseed.bnbchain.org
    - https://bsc-dataseed1.bnbchain.org
    - https://bsc-dataseed2.bnbchain.org
    - https://bsc-dataseed3.bnbchain.org
    - https://bsc-dataseed4.bnbchain.org
    symbol: BSC
    type: EVM
    safelyConcurrentBlockDelta: 100
    maxConcurrency: 5
    monitorHeightAlarmThr: 100
    httpURL:
      - https://api.bscscan.com/api?apikey=8GPEVE2G239UXQ1EASTKRJUI8K617TVYIF
      - https://api.bscscan.com/api?apikey=E4RPAJ3SHH5ZXJJVWQBSNNJ1315BIDFKEF
      - https://api.bscscan.com/api?apikey=VQB4ECWI78TWYAX4UIMDZX66WYZ2NNDF7H
      - https://api.bscscan.com/api?apikey=EZ649V3FG1Z544DPWCJPHHMY142318G43G

  ETH:
    blockExplorerAddrUrl: https://etherscan.io/address/
    blockExplorerTxUrl: https://etherscan.io/tx/
    blockExplorerUrl: https://etherscan.io/
    chain: ETH
    chainId: "1"
    coinId: 60
    decimal: 18
    fullName: Ethereum
    getPriceKey: ethereum
    handler: ethereum
    icon: https://obstatic.243096.com/mili/images/currency/chain/Ethereum.png
    nativeCurrency: ETH
    netType: main
    proxyCacheTime: 15
    proxyKey: gasOracleETH
    rpcURL:
    - https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
    - https://geth.mytokenpocket.vip
#    - https://rpc.onekey.so/eth
    - https://eth626892d.jccdex.cn
    - https://web3.mytokenpocket.vip
    - https://rpc.flashbots.net
    - https://web3os.tokenpocket.pro
    - https://rpc.ankr.com/eth
    symbol: ETH
    type: EVM
    safelyConcurrentBlockDelta: 30
    maxConcurrency: 1
    monitorHeightAlarmThr: 30
    httpURL:
      - https://api.etherscan.io/api?apikey=M7VFNK3Z4J5AG8JZRQB9E25EEEANJG4KXZ
      - https://api.etherscan.io/api?apikey=NJ4P2RHJ5E1N1Z9WZQTDREWD8KP35W49QW
