server:
  http:
    addr: 0.0.0.0:3003
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8998
    timeout: 1s
data:
  database:
    driver: postgres
    source: host=127.0.0.1 user=postgres password=password dbname=wallets port=15433 sslmode=disable TimeZone=Asia/Shanghai
#    source: host=127.0.0.1 user=postgres password=haobtc.asd dbname=blockcrawling port=5432 sslmode=disable TimeZone=Asia/Shanghai
    pool:
      connMaxLifetime: 3
      maxOpenConns: 10
      maxIdleConns: 10
  redis:
    address: 127.0.0.1:6379
    db: 0
    password: ""
    read_timeout: 0.2s
    write_timeout: 0.2s
  user:
    driver: postgres
    source: host=127.0.0.1 user=postgres password=password dbname=wallets port=15433 sslmode=disable TimeZone=Asia/Shanghai
    pool:
      connMaxLifetime: 3
      maxOpenConns: 10
      maxIdleConns: 10

app:
  # Possible values: "debug", "release"
  pattern: "debug"
  mode: ""
  scanAll: false
  addr: 127.0.0.1:9001
  marketRpc: 10.10.2.77:9011
  bfstationRpc: 10.10.2.80:9381
  defiPlatformInteractionThr: 1
  starScan: true
  dogeKey:  # DEPRECATED @2022-09-29: HAVE BEEN MOVED TO THERE URL.
    - "Bearer bd1bd2JBVNTa8XTPQOI7ytO8mK5AZpSpQ14sOwZn2CqD0Cd"
    - "Bearer bd1bBH8zDd2J2BDx2pX9ERgPCY0kSDwBkgvWo5cWypHrLjk"
    - "Bearer bd1aVy9tvRY7WkuPNe2CQRsgb3tQKpYXWS5bT15seqSMrkz"
    - "Bearer bd1bIoqNrQkip0utr61Toh6oN85O9Clm1y1Ty0entqFPSlU"
    - "Bearer bd1bsqxVyRAGqrEwfVRhClEhuZ0wIFhug8uiw9l665OXFYQ"
    - "Bearer bd1boNssO6THUBKd3Gr02LFrniEZgQ9E301p3ja4R72qQPN"
    - "Bearer bd1bib9hNBb6rTeWQ7zarCgWZq7j0tKfdUVfPqnaxXtdDmn"

  # Search 'chain": "evm"' on this page:
  # https://gitlab.bixin.com/mili/mpcgate/-/blob/master/user_service/user_serve/chain_config.py
  featuredCustomChain:
    evm8453: Base
    evm534351: ScrollSepoliaTEST
    evm210425: PlatON
    evm8082: ShardeumTEST
    evm4200: Merlin

  cmq:
    queues:
      swapPairs:
        name: trans_on_chain
        # Test
        id: queue-dEAZdQQ9Sz6Wuv9uLv5s86
        # Production
        # id: queue-eXgpKznr5yWieTrjyR5Hsx
      benfenPairs:
        name: benfen_pair_info
        id: queue-DJtXNyPTJtkQ8WuyauuByp
    topic:
      benfenCharge:
        name: benfen_charge_onchain_result
        id: topic-PYecESX5rsgyqs7GSPpe8m
      payCardCharge:
        name: obcard_charge_onchain_result
        id: topic-bZv2d5DoSmRo3YDHToGjTG
      payCardAssem:
        name: obcard_assem_onchain_result
        id: topic-UwQWsxsWuq8dzNGdDZGGns
      payCardTrans:
        name: obpay_trans_onchain_result
        id:  topic-DfBim9dBKXRqEHLpqAFhcf
      payCardRefund:
        name: obcard_refund_onchain_result
        id: topic-9nHdeiiRvSck7afzCkBDTr
    endpoint:
      queuesURL: ""
      benfenTopicURL: ""
      topicURL: ""
      
  chainData:
    gasCoefficient:
      default: 1
      evm4200: 1.2

lark:
  larkAlarmTitle: "测试环境"
  larkHost: ""
  larkSecret: ""
  larkAtList: ""
  larkUids:
    xyz: a964d8f6

  larkSubscriptions:
    EVM:
      uids: [ xyz ]
    TVM:
      uids: [ xyz ]

  lockNum: 64

logger:
  DEBUG: true
  fileName: "stdout"
  level: "info"

eventLogWhiteList:
  ETH: ETH
  BSC: BSC
