server:
  http:
    addr: 0.0.0.0:3001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8999
    timeout: 1s
data:
  database:
    driver: postgres
    source: host=127.0.0.1 user=haobtc password=haobtc.asd dbname=blockcrawling port=5432 sslmode=disable TimeZone=Asia/Shanghai
#    source: host=127.0.0.1 user=postgres password=haobtc.asd dbname=blockcrawling port=5432 sslmode=disable TimeZone=Asia/Shanghai
    pool:
      connMaxLifetime: 3
      maxOpenConns: 10
      maxIdleConns: 10
  redis:
    address: 127.0.0.1:6379
    db: 2
    password: ""
    read_timeout: 0.2s
    write_timeout: 0.2s

app:
  # Possible values: "debug", "release"
  #  mode: "debug"
  mode: "ETHGoerliTEST,BSCTEST,SuiTEST,NervosTEST,zkSyncTEST,ScrollL1TEST,ScrollL2TEST"
  scanAll: false
  addr: 127.0.0.1:9001
  starScan: true
  target: host=127.0.0.1 user=haobtc password=haobtc.asd dbname=blockcrawling port=5432 sslmode=disable TimeZone=Asia/Shanghai
  source: host=127.0.0.1 user=haobtc password=haobtc.asd dbname=mpcwallet port=5432 sslmode=disable TimeZone=Asia/Shanghai
  dogeKey:  # DEPRECATED @2022-09-29: HAVE BEEN MOVED TO THERE URL.
    - "Bearer bd1bd2JBVNTa8XTPQOI7ytO8mK5AZpSpQ14sOwZn2CqD0Cd"
    - "Bearer bd1bBH8zDd2J2BDx2pX9ERgPCY0kSDwBkgvWo5cWypHrLjk"
    - "Bearer bd1aVy9tvRY7WkuPNe2CQRsgb3tQKpYXWS5bT15seqSMrkz"
    - "Bearer bd1bIoqNrQkip0utr61Toh6oN85O9Clm1y1Ty0entqFPSlU"
    - "Bearer bd1bsqxVyRAGqrEwfVRhClEhuZ0wIFhug8uiw9l665OXFYQ"
    - "Bearer bd1boNssO6THUBKd3Gr02LFrniEZgQ9E301p3ja4R72qQPN"
    - "Bearer bd1bib9hNBb6rTeWQ7zarCgWZq7j0tKfdUVfPqnaxXtdDmn"

lark:
  larkAlarmTitle: "BlockCrawling 测试环境"
  larkHost: "https://open.larksuite.com/open-apis/bot/v2/hook/1de00c8b-8b00-42e8-a4a0-111a465303d9"
#  larkHost: "https://open.larksuite.com/open-apis/bot/v2/hook/1de00c8b-8b00-42e8-a4a0-111a465303d9_"
  larkSecret: "ZaIgbNX9rwSyOGhq4URhMb"
  larkAtList: "9674c624"
  lockNum: 64

logger:
  DEBUG: true
  fileName: "block-crawling.log"
  level: "info"

innerNodeList:
  BTC:
    chain: "BTC"
    decimal: 8
    fullName: "Bitcoin"
    getPriceKey: "bitcoin"
    chainName: "BTC"
    handler: "bitcoin"
    nativeCurrency: BTC
    rpcURL:
      - "http://haotech:phzxiTvtjqHikHTBTnTthqsUHTY2g3@chain01.openblock.top:8332"
    symbol: "BTC"
    type: "BTC"

  DOGE:
    chain: "DOGE"
    decimal: 8
    fullName: "Dogecoin"
    getPriceKey: "dogecoin"
    chainName: "DOGE"
    handler: "dogecoin"
    nativeCurrency: DOGE
    rpcURL:
      - "http://haotech:jHoNTnHnZZY6pXsdfsopweuiUWoUwZKC@chain01.openblock.top:22555"
    symbol: DOGE
    type: "BTC"

  LTC:
    chain: "LTC"
    decimal: 8
    fullName: "litecoin"
    getPriceKey: "litecoin"
    chainName: "LTC"
    handler: "litecoin"
    nativeCurrency: LTC
    rpcURL:
      - "http://haotech:BFHsdfsUYTBN2HbaTZBvHJER4fyHy@chain01.openblock.top:9332"
    symbol: LTC
    type: "BTC"

innerPublicNodeList:
  Cronos:
    blockExplorerAddrUrl: https://cronoscan.com/address/
    blockExplorerTxUrl: https://cronoscan.com/tx/
    blockExplorerUrl: https://cronoscan.com/
    chain: Cronos
    chainId: 25
    coinId: 60
    decimal: 18
    fullName: Cronos
    getPriceKey: Cronos
    handler: cronos
    icon: https://bxhp.243096.com/mili/images/currency/chain/Cronos.png
    nativeCurrency: CRO
    netType: main
    rpcURL:
      - https://cronosrpc-1.xstaking.sg
    symbol: CRO
    type: EVM
