// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.4.0
// - protoc             v3.19.4
// source: helloworld/v1/greeter.proto

package v1

import (
	v1 "block-crawling/api/common/v1"
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGreeterAddUser = "/helloworld.v1.Greeter/AddUser"
const OperationGreeterBatchAddOrUpdateUser = "/helloworld.v1.Greeter/BatchAddOrUpdateUser"
const OperationGreeterGetUser = "/helloworld.v1.Greeter/GetUser"

type GreeterHTTPServer interface {
	AddUser(context.Context, *UserRequest) (*v1.Int64Response, error)
	BatchAddOrUpdateUser(context.Context, *UserRequests) (*v1.Int64Response, error)
	GetUser(context.Context, *UserRequest) (*UserRespose, error)
}

func RegisterGreeterHTTPServer(s *http.Server, srv GreeterHTTPServer) {
	r := s.Route("/")
	r.GET("/user/get/{id}", _Greeter_GetUser0_HTTP_Handler(srv))
	r.POST("/user/add", _Greeter_AddUser0_HTTP_Handler(srv))
	r.POST("/user/batchAddOrUpdate", _Greeter_BatchAddOrUpdateUser0_HTTP_Handler(srv))
}

func _Greeter_GetUser0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterGetUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUser(ctx, req.(*UserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserRespose)
		return ctx.Result(200, reply)
	}
}

func _Greeter_AddUser0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterAddUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddUser(ctx, req.(*UserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.Int64Response)
		return ctx.Result(200, reply)
	}
}

func _Greeter_BatchAddOrUpdateUser0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserRequests
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterBatchAddOrUpdateUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchAddOrUpdateUser(ctx, req.(*UserRequests))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.Int64Response)
		return ctx.Result(200, reply)
	}
}

type GreeterHTTPClient interface {
	AddUser(ctx context.Context, req *UserRequest, opts ...http.CallOption) (rsp *v1.Int64Response, err error)
	BatchAddOrUpdateUser(ctx context.Context, req *UserRequests, opts ...http.CallOption) (rsp *v1.Int64Response, err error)
	GetUser(ctx context.Context, req *UserRequest, opts ...http.CallOption) (rsp *UserRespose, err error)
}

type GreeterHTTPClientImpl struct {
	cc *http.Client
}

func NewGreeterHTTPClient(client *http.Client) GreeterHTTPClient {
	return &GreeterHTTPClientImpl{client}
}

func (c *GreeterHTTPClientImpl) AddUser(ctx context.Context, in *UserRequest, opts ...http.CallOption) (*v1.Int64Response, error) {
	var out v1.Int64Response
	pattern := "/user/add"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterAddUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *GreeterHTTPClientImpl) BatchAddOrUpdateUser(ctx context.Context, in *UserRequests, opts ...http.CallOption) (*v1.Int64Response, error) {
	var out v1.Int64Response
	pattern := "/user/batchAddOrUpdate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterBatchAddOrUpdateUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *GreeterHTTPClientImpl) GetUser(ctx context.Context, in *UserRequest, opts ...http.CallOption) (*UserRespose, error) {
	var out UserRespose
	pattern := "/user/get/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGreeterGetUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
